#!/bin/sh
#Wallch WallpaperChanger -A tool for having fun changing desktop wallpapers-
#Copyright © 2010-2011 by Leon Vytanos and Alex Solanos
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 3
#of the License, or (at your option) any later version.
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
a=`cat /home/$USER/.config/Wallch/Checks/double`
if [ X"$a" = X"$(gconftool-2 --get /desktop/gnome/background/picture_filename)" ]; then
exit 2; #the image is already desktop background
fi
if [ X"$(pidof setupwallpaper)" != X"" ]; then
exit 2; #live earth wallpaper is running
fi
notification=`sed -n '2p' /home/$USER/.config/Wallch/Settings`;
play_sound=`sed -n '4p' /home/$USER/.config/Wallch/Settings`
keep_history=`sed -n '5p' /home/$USER/.config/Wallch/Settings`
history_path=`cat /home/$USER/.config/Wallch/Checks/history_custom_path`
if [ -s "$history_path" ]; then false
else
if [ X"$history_path" != X"" ]; then
echo "History path not valid! $history_path does not exist! Saving the history at /home/$USER/.config/Wallch/History/";
mkdir -p /home/$USER/.config/Wallch/History/
fi
history_path="/home/$USER/.config/Wallch/History/"
fi
if [ X"$notification" = X"Show notification: True" ]; then
killall -v notify-osd 2> /dev/null
language=`sed -n '1p' /home/$USER/.config/Wallch/Settings`
if [ X"$language" = X"Language: Greek" ]; then
notify-send "Η εικόνα της επιφάνειας εργασίας σας έχει μόλις αλλάξει στην εικόνα αριστερά!" -i "$a";
else  notify-send "Your Desktop Wallpaper has just changed to the image shown on the left." -i "$a"
fi
fi
if [ X"$play_sound" = X"Play Sound: True" ]; then
canberra-gtk-play -f /usr/share/wallch/files/notification.ogg&
fi
if [ X"$play_sound" = X"Play Sound: True + Custom Sound" ]; then
soundfile=`cat /home/$USER/.config/Wallch/Checks/text_to_button`
ext_of_file=`echo $soundfile | sed -n 's/\(^.[^$]*\)\(.\{3\}$\)/\2/p'`
if [ X"$ext_of_file" = X"mp3" -o X"$ext_of_file" = X"MP3" ]; then
mpg123 "$soundfile" 2> /dev/null& fi
if [ X"$ext_of_file" = X"wav" -o X"$ext_of_file" = X"ogg" -o X"$ext_of_file" = X"WAV" -o X"$ext_of_file" = X"OGG" ]; then
canberra-gtk-play -f "$soundfile"&
fi
fi
if [ X"$keep_history" != X"Keep history of: none" ]; then
if [ `date '+%a'` = "Mon" ]; then now="Mondays"; fi
if [ `date '+%a'` = "Tue" ]; then now="Tuesdays"; fi
if [ `date '+%a'` = "Wed" ]; then now="Wednesdays"; fi
if [ `date '+%a'` = "Thu" ]; then now="Thursdays"; fi
if [ `date '+%a'` = "Fri" ]; then now="Fridays"; fi
if [ `date '+%a'` = "Sat" ]; then now="Saturdays"; fi
if [ `date '+%a'` = "Sun" ]; then now="Sundays"; fi
if [ X"$history_path" != X"" ]; then #if there is custom history path specified and does exist
if [ X"$keep_history" = X"Keep history of: month" ]; then
echo {Set as Desktop background by hand} `date '+%h'` Image:$a $notification $play_sound >> "$history_path"/History_$now
fi
if [ X"$keep_history" = X"Keep history of: monthenday" ]; then
echo {Set as Desktop background by hand} `date '+%a'` `date '+%d'` `date '+%h'` Image:$a $notification $play_sound >> "$history_path"/History_$now
fi
if [ X"$keep_history" = X"Keep history of: monthendayentime" ]; then
echo {Set as Desktop background by hand} `date '+%a'` `date '+%d'` `date '+%h'` `date '+%r'` Image:$a $notification $play_sound >> "$history_path"/History_$now
fi
if [ X"$keep_history" = X"Keep history of: monthendayentimeensecs" ]; then
echo {Set as Desktop background by hand} `date '+%a'` `date '+%d'` `date '+%h'` `date '+%r'` `date '+%s'` Image:$a $notification $play_sound >> "$history_path"/History_$now
fi
fi #END of if there is path specified
fi
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$a"; rm /home/$USER/.config/Wallch/Checks/double
