#!/bin/sh
#Wallch WallpaperChanger -A tool for having fun changing desktop wallpapers-
#Copyright © 2010-2011 by Leon Vytanos and Alex Solanos
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 3
#of the License, or (at your option) any later version.
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [ -d /home/$USER/.config/autostart ]; then
false
else
mkdir -p /home/$USER/.config/autostart/
fi
echo "#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=WallPaperChanger
Comment=A program to change your desktop wallpapers...!
Exec=/usr/share/wallch/files/Scripts/boot_wallpaper_changer
Terminal=false
Type=Application
Icon=/usr/share/wallch/files/wallpaper.png
Categories=Application;Accessories;Utility;
StartupNotify=false
Name[en_US]=Wallpaper Changer
X-GNOME-Autostart-enabled=true" > /home/$USER/.config/autostart/WallpaperChangerOnBoot.desktop
