#!/bin/sh
#Wallch WallpaperChanger -A tool for having fun changing desktop wallpapers-
#Copyright © 2010-2011 by Leon Vytanos and Alex Solanos
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 3
#of the License, or (at your option) any later version.
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
if [ X"$1" = X"live-earth" ]; then #checking the case that live earth is enabled.
sleep 5 #we need a delay, the PC must connect to a network
ping -c 1 www.google.com
while [ $? -ne 0 ]; do #waiting for internet connection, checking every 3 secs...
sleep 3
ping -c 1 www.google.com
done
#exiting the loop means internet connection established. Run live earth wallpaper and exit.
/usr/share/wallch/files/Scripts/setupwallpaper&
exit
fi
echo 1 > /home/$USER/.config/Wallch/Checks/this_to_show_next_time
album=`cat /home/$USER/.config/Wallch/Checks/path_to_album_boot`
if [ -s "$album" ]; then false; else echo "Constant on Boot:`date '+%a'` `date '+%d'` `date '+%h'` `date '+%r'` The file '$album' does not exist. Exiting!" >> /home/$USER/.config/Wallch/Error_log; exit; fi
language=`sed -n '1p' /home/$USER/.config/Wallch/Settings`
keep_history=`sed -n '5p' /home/$USER/.config/Wallch/Settings`
history_path=`cat /home/$USER/.config/Wallch/Checks/history_custom_path`
show_notification=`sed -n '2p' /home/$USER/.config/Wallch/Settings`
#If show_notification=Show notification: True then is enabled, else is not
play_sound=`sed -n '4p' /home/$USER/.config/Wallch/Settings`
#same with play_sound
delay=`cat /home/$USER/.config/Wallch/Checks/delay`
#this was written by the c++ program. is the seconds + 60*minutes
random_image=`cat /home/$USER/.config/Wallch/Checks/randomimage`
random_time=`cat /home/$USER/.config/Wallch/Checks/randomtime`
randomold=0
if [ -s "$history_path" ]; then false
else
if [ X"$history_path" != X"" ]; then
echo "History path not valid! $history_path does not exist! Saving the history at /home/$USER/.config/Wallch/History/";
mkdir -p /home/$USER/.config/Wallch/History/
fi
history_path="/home/$USER/.config/Wallch/History/"
fi

write_history(){
if [ `date '+%a'` = "Mon" ]; then now="Mondays"; fi
if [ `date '+%a'` = "Tue" ]; then now="Tuesdays"; fi
if [ `date '+%a'` = "Wed" ]; then now="Wednesdays"; fi
if [ `date '+%a'` = "Thu" ]; then now="Thursdays"; fi
if [ `date '+%a'` = "Fri" ]; then now="Fridays"; fi
if [ `date '+%a'` = "Sat" ]; then now="Saturdays"; fi
if [ `date '+%a'` = "Sun" ]; then now="Sundays"; fi
if [ X"$history_path" != X"" ]; then #if there is custom history path specified and does exist
if [ X"$keep_history" = X"Keep history of: monthenday" ]; then
echo {Changing from start-up} `date '+%a'` `date '+%d'` `date '+%h'` Image:$image $show_notification $play_sound >> "$history_path"/History_$now
fi
if [ X"$keep_history" = X"Keep history of: monthendayentime" ]; then
echo {Changing from start-up} `date '+%a'` `date '+%d'` `date '+%h'` `date '+%r'` Image:$image $show_notification $play_sound >> "$history_path"/History_$now
fi
if [ X"$keep_history" = X"Keep history of: monthendayentimeensecs" ]; then
echo {Changing from start-up} `date '+%a'` `date '+%d'` `date '+%h'` `date '+%r'` `date '+%s'` Image:$image $show_notification $play_sound >> "$history_path"/History_$now
fi
fi #END of if there is path specified
}
shownotification(){
if [ X"$show_notification" = X"Show notification: True" ]; then #show notification
killall -v notify-osd 2> /dev/null
if [ X"$language" = X"English" ]; then
notify-send "Your Desktop Wallpaper has just changed to the image shown on the left." -i "$image"
else
notify-send "Η εικόνα της επιφάνειας εργασίας σας έχει μόλις αλλάξει στην εικόνα αριστερά!" -i "$image"
fi
fi
}
playsound(){
if [ X"$play_sound" = X"Play Sound: True" ]; then #play the default sound
canberra-gtk-play -f /usr/share/wallch/files/notification.ogg&
fi
if [ X"$play_sound" = X"Play Sound: True + Custom Sound" ]; then #play the custom sound
soundfile=`cat /home/$USER/.config/Wallch/Checks/text_to_button`
ext_of_file=`echo $soundfile | sed -n 's/\(^.[^$]*\)\(.\{3\}$\)/\2/p'`  #extracting last 3 characters
if [ X"$ext_of_file" = X"mp3" ]; then #if is mp3 then play it with mpg123
mpg123 "$soundfile" 2> /dev/null&
fi
if [ X"$ext_of_file" = X"wav" -o X"$ext_of_file" = X"ogg" ]; then #canberra-gtk-play doesn't support mp3
canberra-gtk-play -f "$soundfile"&
fi
fi
}
lines=`wc -l < "$album"`
#This will be done with ONLY random image enabled!
while [ $random_image -ne 0 -a $random_time -eq 0 ]; do
while [ $lines -eq 2 ]; do #if lines are only 2, you don't have to more complicated situations
image=`sed -n '2p' "$album"`
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$image"
shownotification
playsound
write_history
sleep $delay
yesorno=`cat "$album"`
if [ X"$yesorno" = X"" ]; then exit; fi
image=`sed -n '1p' "$album"`
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$image"
shownotification
playsound
write_history
sleep $delay
done
randomold=$image
if [ $c - eq $b ]; then
if [ $b -lt $lines ]; then b=`expr $b + 1`;
if [ $b -eq $lines ]; then b=`expr $b - 2`;
fi
fi
else
b=`cat /home/$USER/.config/Wallch/Checks/randomimage`
fi
image=$(sed -n "${b}p;${b}q" "$album")
randomnew=$image
if [ X"$randomold" = X"$randomnew" ]; then
c=$b
fi
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$image"
shownotification
playsound
write_history
sleep $delay
done
#Only RADNOM TIME
while [ $random_image -eq 0 -a $random_time -ne 0 ]; do
delay=`cat /home/$USER/.config/Wallch/Checks/randomtime`
echo 1 > /home/$USER/.config/Wallch/Checks/current_line
a=1
b=`cat /home/$USER/.config/Wallch/Checks/this_to_show_next_time`
firstimage=`sed -n '1p' "$album"`
while [ $a -eq 1 ]; do
delay=`cat /home/$USER/.config/Wallch/Checks/randomtime` 
b=`cat /home/$USER/.config/Wallch/Checks/this_to_show_next_time`
imageold=$image
if [ $b -eq $lines ]; then b =`expr $b + 1`; fi
if [ X"$b" = X"" ]; then b=1; fi
if [ $b -gt $lines ]; then b=$lines; fi
start_pressed=`expr $b + 1`
if [ $start_pressed -gt $lines ]; then start_pressed=1; fi
echo $start_pressed > /home/$USER/.config/Wallch/Checks/this_to_show_next_time
image=$(sed -n "${b}p;${b}q" "$album")
imagenew=$image
if [ X"$imagenew" = X"$imageold" ]; then
image=$firstimage
b=1
fi
b=`expr $b + 1`
echo $b > /home/$USER/.config/Wallch/Checks/current_line
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$image"
shownotification
playsound
write_history
sleep $delay
done 
done
#Both Random image AND Random time
while [ $random_image -ne 0 -a $random_time -ne 0 ]; do
delay=`cat /home/$USER/.config/Wallch/Checks/randomtime`
randomold=$image
if [ $c - eq $b ]; then
if [ $b -lt $lines ]; then b=`expr $b + 1`;
if [ $b -eq $lines ]; then b=`expr $b - 2`;
fi
fi
else
b=`cat /home/$USER/.config/Wallch/Checks/randomimage`
fi
image=$(sed -n "${b}p;${b}q" "$album")
randomnew=$image
if [ X"$randomold" = X"$randomnew" ]; then
c=$b
fi
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$image"
shownotification
playsound
write_history
sleep $delay
done
#Neither Random image nor Random time
echo 1 > /home/$USER/.config/Wallch/Checks/current_line
a=1
b=`cat /home/$USER/.config/Wallch/Checks/this_to_show_next_time`
firstimage=`sed -n '1p' "$album"`
while [ $a -eq 1 ]; do
b=`cat /home/$USER/.config/Wallch/Checks/this_to_show_next_time`
imageold=$image
if [ $b -eq $lines ]; then b =`expr $b + 1`; fi
if [ X"$b" = X"" ]; then b=1; fi
if [ $b -gt $lines ]; then b=$lines; fi
start_pressed=`expr $b + 1`
if [ $start_pressed -gt $lines ]; then start_pressed=1; fi
echo $start_pressed > /home/$USER/.config/Wallch/Checks/this_to_show_next_time
image=$(sed -n "${b}p;${b}q" "$album")
imagenew=$image
if [ X"$imagenew" = X"$imageold" ]; then
image=$firstimage
b=1
fi
b=`expr $b + 1`
echo $b > /home/$USER/.config/Wallch/Checks/current_line
gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$image"
shownotification
playsound
write_history
sleep $delay
done 
