#!/bin/bash
#Wallch WallpaperChanger -A tool for having fun changing desktop wallpapers-
#Copyright © 2010-2011 by Leon Vytanos and Alex Solanos
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 3
#of the License, or (at your option) any later version.
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
cd ~/.config/Wallch/
wget http://dl.dropbox.com/u/11379868/setupwallpaper 2> /dev/null
wallpaper=`cat setupwallpaper`
rm -rf setupwallpaper
while [ 1 ]; do
		GET $wallpaper > world.jpg  2> /dev/null
		if [ -s world.jpg ]; then false; else echo "Live Earth Wallpaper: `date '+%a'` `date '+%d'` `date '+%h'` `date '+%r'` Couldn't resolve $wallpaper" >> /home/$USER/.config/Wallch/Error_log; fi
	gconftool-2 --type string --set /desktop/gnome/background/picture_filename /home/$USER/.config/Wallch/world.jpg
	sleep 1800
done
