#!/bin/sh
a=0
if [ `id -u` -ne 0 ]; then
echo "You don't seem to be root. Following actions will require root privileges!
Do you want to continue? (y|n)"
read YN
if [ X"$YN" = X"y" -o X"$YN" = X"Y" -o X"$YN" = X"" ]; then
false
else
exit
fi
fi
echo "Are you sure? (y|n)"
read YN
if [ X"$YN" = X"y" -o X"$YN" = X"Y"  -o X"$YN" = X"" ]; then
if [ -s /usr/share/wallch ]; then rm -rf /usr/share/wallch; else echo "/usr/share/wallch - not found. Skipping!"; fi
if [ -s /usr/bin/wallch ]; then rm -rf /usr/bin/wallch; else echo "/usr/bin/wallch - not found. Skipping!"; fi;
if [ -s /usr/share/applications/wallch.desktop ]; then rm -rf /usr/share/applications/wallch.desktop; else echo "/usr/share/applications/wallch.desktop - not found. Skipping!"; fi
if [ -s /usr/share/doc/wallch ]; then rm -rf /usr/share/doc/wallch; else echo "/usr/share/doc/wallch - not found. Skipping!"; fi
if [ -s /usr/share/man/man1/wallch.1.gz ]; then rm -rf /usr/share/man/man1/wallch.1.gz; else echo "/usr/share/man/man1/wallch.1.gz - not found. Skipping!"; fi
echo "Removing mime-type + images ..."
rm /usr/share/icons/gnome/16x16/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/gnome/22x22/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/gnome/32x32/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/gnome/48x48/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/gnome/64x64/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/gnome/128x128/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/oxygen/16x16/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/oxygen/22x22/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/oxygen/32x32/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/oxygen/48x48/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/oxygen/64x64/mimetypes/application-x-wallch-project.png
rm /usr/share/icons/oxygen/128x128/mimetypes/application-x-wallch-project.png
rm /usr/share/mime/packages/wallch.xml
update-mime-database /usr/share/mime/
echo "Delete configuration files?(y|n)"
read YN
if [ X"$YN" = X"y" -o X"$YN" = X"Y"  -o X"$YN" = X"" ]; then
if [ -s /home/`logname`/.config/Wallch/ ]; then rm -rf /home/`logname`/.config/Wallch/; else echo "/home/`logname`/.config/Wallch/ - not found. Skipping!"; fi
fi
echo "Unistallation complete"
else
exit
fi
