#!/bin/sh
a=0
if [ $(id -u) -ne 0 ]; then
echo "You don't seem to be root. Following actions will require root privileges!
Do you want to continue? (y|n)"
read YN
if [ X"$YN" = X"y" -o X"$YN" = X"Y" -o X"$YN" = X"" ]; then
false
else
exit
fi
fi
echo "Are you sure? (y|n)"
read YN
if [ X"$YN" = X"y" -o X"$YN" = X"Y"  -o X"$YN" = X"" ]; then
if [ -s /usr/local/share/wallch ]; then rm -rf /usr/local/share/wallch; else echo "/usr/local/share/wallch - not found. Skipping!"; fi
if [ -s /usr/bin/wallch ]; then rm -rf /usr/bin/wallch; else echo "/usr/bin/wallch - not found. Skipping!"; fi;
if [ -s /usr/share/applications/wallch.desktop ]; then rm -rf /usr/share/applications/wallch.desktop; else echo "/usr/share/applications/wallch.desktop - not found. Skipping!"; fi
if [ -s /usr/share/doc/wallch ]; then rm -rf /usr/share/doc/wallch; else echo "/usr/share/doc/wallch - not found. Skipping!"; fi
if [ -s /etc/wallch ]; then rm -rf /etc/wallch; else echo "/etc/wallch - not found. Skipping!"; fi;
if [ -s /usr/share/man/man1/wallch.1.gz ]; then rm -rf /usr/share/man/man1/wallch.1.gz; else echo "/usr/share/man/man1/wallch.1.gz - not found. Skipping!"; fi
if [ -s /usr/share/gnome/help/wallch ]; then rm -rf /usr/share/gnome/help/wallch; else echo "/usr/share/gnome/help/wallch - not found. Skipping!"; fi
if [ -s /etc/bash_completion.d/wallch ]; then rm -rf /etc/bash_completion.d/wallch; else echo "/etc/bash_completion.d/wallch - not found. Skipping!"; fi
rm -f /usr/share/icons/hicolor/16x16/mimetypes/application-x-wallch-project.png
rm -f /usr/share/icons/hicolor/22x22/mimetypes/application-x-wallch-project.png
rm -f /usr/share/icons/hicolor/32x32/mimetypes/application-x-wallch-project.png
rm -f /usr/share/icons/hicolor/48x48/mimetypes/application-x-wallch-project.png
rm -f /usr/share/icons/hicolor/64x64/mimetypes/application-x-wallch-project.png
rm -f /usr/share/icons/hicolor/128x128/mimetypes/application-x-wallch-project.png
rm -f /usr/share/mime/packages/wallch.xml
update-mime-database /usr/share/mime/
echo "Unistallation complete, thanks for using Wallch. If something didn't satisfy you, please let us know at wallch.developers@gmail.com"
else
exit
fi
